FROM ruby:2.5-alpine

RUN apk update && apk add build-base nodejs postgresql-dev tzdata

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install --binstubs

COPY . .

LABEL maintainer="Hendrik Kleinwaechter <hendrik.kleinwaechter@trivago.com>"

CMD puma -C config/puma.rb
